//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity___Legacy_DB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Users1 = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Deletable { get; set; }
        public bool active { get; set; }
        public Nullable<int> IntroducerID { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<bool> LogonToWindowsApplication { get; set; }
        public Nullable<bool> LogonToPortal { get; set; }
        public Nullable<bool> PasswordIsEncrytped { get; set; }
        public bool ViewAllUsers { get; set; }
        public Nullable<int> UserTemplateID { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public bool IsTeamUser { get; set; }
        public Nullable<System.DateTime> StartWorkTime { get; set; }
        public Nullable<System.DateTime> EndWorkTime { get; set; }
        public int CallbackMaxWorkingDaysAhead { get; set; }
        public bool ForcePasswordReset { get; set; }
        public Nullable<int> LastModifiedByUserID { get; set; }
        public Nullable<System.DateTime> LastModifiedTime { get; set; }
        public Nullable<int> DefaultInsolvencyPractitionerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
